### ISSUE TITLE
Handle an instance where location that is typed is not found

### ISSUE THREAD

**Issue by grace-omotoso** [MLH-Fellowship/prep-project-4.1.3#24]
If I type a location that does not exist in the search bar, the app keeps loading indefinitely. We can handle this using one of two ways:
- Set back the location to the default if new york
- display a message that "Location is not found"

**Comment by saikeshari** [comment]
@grace-omotoso We have also implemented this in the merged PR.
Let us know if we should do some enhancement in this.
