### ISSUE TITLE
Add a name and logo to the webapp

### ISSUE THREAD

**Issue by SciencePotato** [MLH-Fellowship/prep-project-4.1.3#36]
We can add a logo to our weather app and also give it a name to make the project more complete.
@sumana2001  and I have also added an issue for PWA, to make the website into an app that can be downloaded for which was also we'll need a logo. If you feel this is something we can add to our website, please assign issue #32  and this issue to @sumana2001 and me

**Comment by grace-omotoso** [comment]
If there are more pressing issues, I prefer you do those before issue #32. So you can work on this first.

**Comment by SciencePotato** [comment]
![image](https://user-images.githubusercontent.com/64312205/142775286-20d6044a-5495-48cb-89ce-8160cc19f1e4.png)
@grace-omotoso I've created some rough outlines for the logo. The color is not yet set, if any of these is good enough I'll proceed to make it a more detailed version of it. If not please let me know.

**Comment by grace-omotoso** [comment]
@sumana2001 This looks okay, you can integrate it into the app and raise a draft PR
