### ISSUE TITLE
Suggestion box and Map are overlapping for small screen 

### ISSUE THREAD

**Issue by neha-93** [MLH-Fellowship/prep-project-4.1.3#49]
![Screenshot (315)](https://user-images.githubusercontent.com/69652168/142875742-92892272-ba97-45a8-9dae-bc49b2a61add.png)

For smaller screen sizes the suggestion box for autocompletion is being overlapped with the map.

**Comment by GrayFlash** [comment]
@neha-93 and @grace-omotoso made a pr please check it once for potential suggestions
